import { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { useRef } from 'react';
import { checkPassword } from '../../api/auth';
import Button from '../../components/common/Button';
import FormInput from '../../components/common/FormInput';
import Title from '../../components/common/Title';

const CheckPw: NextPage = ({}) => {
  const passwordInputRef = useRef<HTMLInputElement>(null);
  const router = useRouter();

  async function submitHandler(event: React.SyntheticEvent) {
    event.preventDefault();
    const enteredPassword = (passwordInputRef.current as HTMLInputElement)
      .value;
    if (enteredPassword.trim().length === 0) {
      alert('입력을 해주세요.');
      return;
    }
    try {
      const response = await checkPassword({ password: enteredPassword });
      if (response.data === '인증되었습니다') {
        router.push(
          {
            pathname: '/user/resetpw',
            query: { pwck_state: response.data },
          },
          '/user/resetpw'
        );
      } else {
        alert('비밀번호를 다시 확인해주세요.');
      }
    } catch (error) {
      alert('다시 시도해주세요.');
    }
  }

  return (
    <>
      <Head>
        <title>비밀번호 확인</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo.png" />
      </Head>
      <main>
        <Title>비밀번호 확인</Title>
        <form
          onSubmit={submitHandler}
          className="flex flex-col justify-center items-center"
        >
          <div>
            <FormInput
              label="비밀번호"
              id="password"
              type="password"
              ref={passwordInputRef}
            ></FormInput>
          </div>
          <div className="flex justify-center content-center">
            <Link href="/user/mypage">
              <Button
                label="취소"
                btnType="normal"
                btnSize="medium"
                type="button"
              ></Button>
            </Link>
            <Button
              label="확인"
              btnType="active"
              btnSize="medium"
              type="submit"
            ></Button>
          </div>
        </form>
      </main>
    </>
  );
};

export default CheckPw;
