import { NextPage } from 'next';
import Head from 'next/head';
import Title from '../components/common/Title';

const About: NextPage = ({}) => {
  return (
    <>
      <Head>
        <title>알록달록 소개</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo.png" />
      </Head>
      <main>
        <Title>알록달록이란?</Title>
      </main>
    </>
  );
};

export default About;
