import { NextPage } from 'next';
import Head from 'next/head';
import FormInput from '../components/common/FormInput';
import Button from '../components/common/Button';

const Login: NextPage = ({}) => {
  return (
    <>
      <Head>
        <title>로그인</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo.png" />
      </Head>
      <main>
        <div className="text-center font-custom font-bold text-lg text-black mb-12">
          로그인
        </div>
        <form className="flex flex-col justify-center items-center">
          <FormInput label="이메일" id="email"></FormInput>
          <FormInput label="비밀번호" id="password" type="password"></FormInput>
        </form>

        <div className="flex justify-center content-center">
          <Button label="회원가입" btnType="normal" btnSize="medium"></Button>
          <Button label="확인" btnType="active" btnSize="medium"></Button>
        </div>
        <div className="flex justify-center content-center m-2 font-custom font-medium text-sm text-gray-dark">
          비밀번호 찾기
        </div>
      </main>
    </>
  );
};

export default Login;
