import { NextPage } from 'next';
import Head from 'next/head';
import Button from '../components/common/Button';
import Board from '../components/common/Board';
import ListCard from '../components/common/ListCard';

const MyPage: NextPage = ({}) => {
  return (
    <>
      <Head>
        <title>마이페이지</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo.png" />
      </Head>
      <main>
        <div className="text-center font-custom font-bold text-lg text-black mb-12">
          마이페이지
        </div>
        <div className="flex mb-8">
          <div className="flex items-center font-custom font-bold text-xl mr-4">
            nickname 님 안녕하세요!
          </div>
          <Button
            label="내 정보 확인"
            btnType="normal"
            btnSize="medium"
          ></Button>
          <Button
            label="비밀번호 수정"
            btnType="normal"
            btnSize="medium"
          ></Button>
        </div>
        <div className="flex flex-col mb-8">
          <div className="flex items-center font-custom font-bold text-xl mb-4">
            내 지갑
          </div>
          <Board>
            <div className="flex flex-row mb-4">
              <div className="font-custom font-bold text-lg text-left mr-20">
                잔액
              </div>
              <div className="font-custom font-medium text-lg mr-2">
                10,000 ETH
              </div>
              <Button label="충전" btnType="active" btnSize="small"></Button>
            </div>
            <div className="flex flex-row">
              <div className="font-custom font-bold text-lg text-left mr-6">
                내 지갑 주소
              </div>
              <div className="font-custom font-medium text-lg">
                sdfkwefkpwfk10fanklefaewo;jfaowefjawjfopa
              </div>
            </div>
          </Board>
        </div>
        <div className="flex flex-col mb-8">
          <div className="flex items-center font-custom font-bold text-xl mb-4">
            내가 등록한 자물쇠
          </div>
          <ListCard
            tag="#광주"
            title="
        긴 제목입니다.
        긴 제목입니다.
        긴 제목입니다.
        긴 제목입니다.
        긴 제목입니다.
        긴 제목입니다.
        긴 제목입니다.
        "
            content="
        아무 내용없는 긴내용입니다.아무 내용없는 긴내용입니다.아무 내용없는 긴내용입니다.아무 내용없는 긴내용입니다.아무 내용없는 긴내용입니다.아무 내용없는 긴내용입니다.
        아무 내용없는 긴내용입니다.아무 내용없는 긴내용입니다.아무 내용없는 긴내용입니다.아무 내용없는 긴내용입니다.아무 내용없는 긴내용입니다.아무 내용없는 긴내용입니다.
        "
          />
          <ListCard
            tag="#광주"
            title="
        긴 제목입니다.
        긴 제목입니다.
        긴 제목입니다.
        긴 제목입니다.
        긴 제목입니다.
        긴 제목입니다.
        긴 제목입니다.
        "
            content="
        아무 내용없는 긴내용입니다.아무 내용없는 긴내용입니다.아무 내용없는 긴내용입니다.아무 내용없는 긴내용입니다.아무 내용없는 긴내용입니다.아무 내용없는 긴내용입니다.
        아무 내용없는 긴내용입니다.아무 내용없는 긴내용입니다.아무 내용없는 긴내용입니다.아무 내용없는 긴내용입니다.아무 내용없는 긴내용입니다.아무 내용없는 긴내용입니다.
        "
          />
        </div>
      </main>
    </>
  );
};

export default MyPage;
